package io.veronicacrowe;

/**
 * Created by veronicacrowe on 5/20/16.
 */
public enum calculatorOptions {
    ADD, SUBTRACT, MULTIPLY, DIVIDE, SQUAREROOT, SQUARE, INVERSE, EXPONENT, CLEAR, INVERT, SAVE, RETRIEVE, RESETMEMORY, SIN, COS, TAN, INVERSESINE, INVERSECOS, INVERSETAN, LOG, INVERSELOG, NATURALLOG, INVERSENL, FACTORIAL, DISPLAY, OFF, MENU
}
