package io.veronicacrowe;

/**
 * Created by veronicacrowe on 5/21/16.
 */
public enum Operation {
    ADD, SUBTRACT, MULTIPLY, DIVIDE, SQUAREROOT, SQUARE, INVERSE, EXPONENT, CLEAR, INVERT, SAVE, RETRIEVE, RESETMEMORY,
    SIN, COS, TAN, INVERSESINE, INVERSECOS, INVERSETAN, LOG, INVERSELOG, NATURALLOG, INVERSENL, FACTORIAL, OFF, MENU

}
